version: '3'
services:
  cassandra:
    image: cassandra:latest
    container_name: my-cassandra
    ports:
      - "9042:9042"
    environment:
      - CASSANDRA_CLUSTER_NAME=CassandraCluster
      - CASSANDRA_DC=CassandraDatacenter
      - CASSANDRA_ENDPOINT_SNITCH=GossipingPropertyFileSnitch
    volumes:
      - ./data:/var/lib/cassandra
    networks:
      - cassandra-net

networks:
  cassandra-net:
